version: "3.8"
services:
  backend:
    image: "bogdandanielioan/online-school:18.1.2022.23.7.39"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
