version: "3.8"
services:
  backend:
    image: "bogdandanielioan/online-school:10.1.2022.22.9.46"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
