version: "3.8"
services:
  backend:
    image: "bogdandanielioan/online-school:20.1.2022.11.15.15"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
