version: "3.8"
services:
  backend:
    image: "bogdandanielioan/online-school:11.1.2022.22.37.7"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
