name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  MYSQL_DB: online_school_db
  MYSQL_USER: onlineschool
  MYSQL_PASSWORD: onlineschool
  JAVA_VERSION: 1.15

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DB }}
          MYSQL_ROOT_USER: ${{ env.MYSQL_USER }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run: |
          ./mvnw --no-transfer-progress clean package -P build-frontend
        env:
          CI: false

